### PR TITLE
Fix `is_subgraph_isomorphic` with parallel edges.

### LINKED ISSUE #429: Subgraph isomorphism fails with parallel edges
### Information

- **retworkx version**: main
- **Python version**: Any
- **Rust version**: Any
- **Operating system**: Any

### What is the current behavior?
`is_subgraph_isomorphic` returns `True` even in cases it shouldn't. This happens if the input "small" graph have parallel edges.

### What is the expected behavior?
Handle correctly graphs with parallel edges.

### Steps to reproduce the problem
```python
import retworkx as rx

first = rx.PyGraph()
first.extend_from_edge_list([
    (0, 1), (1, 2), (2, 3)
])
second = rx.PyGraph()
second.extend_from_edge_list([
    (0, 1), (0, 1)
])
rx.is_subgraph_isomorphic(first, second)
---
True
```

### PR DESCRIPTION
**Pull request by georgios-ts**
Closes #429.
The solution is to build an adjacency matrix with entries equal
to the number of edges connecting a pair of nodes instead of
0/1 values.

### CODE REVIEW

File: src/isomorphism/vf2.rs [hunk 1]
```diff
@@ -41,6 +38,48 @@ use crate::iterators::NodeMap;
 
 type StablePyGraph<Ty> = StableGraph<PyObject, PyObject, Ty>;
 
+/// Returns the adjacency_matrix of a graph with `(i, j)` entry equal
+/// to number of edges from node `i` to node `j`.
+fn adjacency_matrix<Ty: EdgeType>(graph: &StablePyGraph<Ty>) -> Vec<usize> {
```
Comment (mtreinish) [inline src/isomorphism/vf2.rs:43]: I'm wondering if instead of using a matrix it would be better to fix #367 as part of this too and just query the graph object to get the edge count on demand. Not sure what the performance difference will be though, but it will at least scale better in the amount of memory required.

**Comment by mtreinish** [comment]
When this is combined with #418 can we drop the fixedbitset dependency from the `Cargo.toml`?

File: src/isomorphism/vf2.rs [hunk 2]
```diff
@@ -41,6 +38,48 @@ use crate::iterators::NodeMap;
...
+    let n = graph.node_bound();
+    let mut matrix = vec![0; n * n];
```
Comment (IvanIsCoding) [inline src/isomorphism/vf2.rs:45]: Because of #367, I would say using a sparse matrix or hashmap would be more appropriate if we stick with the adjacency matrix approach

File: src/isomorphism/vf2.rs (hunk 1 above)
Comment (georgios-ts) [reply src/isomorphism/vf2.rs:43]: Yeah, I thought about it but in the interest of time, I decided to push this fix and in a follow up, once we also have a serious benchmark, we can check if there is a time performance difference using something like `HashMap`

**Comment by georgios-ts** [comment]
This benchmark https://github.com/Qiskit/retworkx/pull/288#issuecomment-804448939 runs in `3.77 sec` with `Vec` while with `HashMap` in `2.64 sec`. So, I switched to `HashMap` in b0745b1 and we can close #367 with this PR.

I addressed also the further bugs reported https://github.com/Qiskit/retworkx/issues/429#issuecomment-910171179 in 538ba51

File: src/isomorphism/vf2.rs [hunk 3]
```diff
@@ -41,6 +38,86 @@ use crate::iterators::NodeMap;
...
+        std::mem::swap(a, b)
+    }
+}
+
+/// Returns the adjacency matrix of a graph as a dictionary
+/// with `(i, j)` entry equal to number of edges from node `i` to node `j`.
+fn adjacency_matrix<Ty: EdgeType>(
+    graph: &StablePyGraph<Ty>,
+) -> HashMap<(NodeIndex, NodeIndex), usize> {
+    let mut matrix = HashMap::with_capacity(graph.edge_count());
```
Comment (mtreinish) [inline src/isomorphism/vf2.rs:79]: Won't this potentially overallocate in the case of parallel edges?

File: src/isomorphism/vf2.rs [hunk 4]
```diff
@@ -41,6 +38,86 @@ use crate::iterators::NodeMap;
...
+    matrix: &HashMap<(NodeIndex, NodeIndex), usize>,
+    a: NodeIndex,
+    b: NodeIndex,
+    val: usize,
+) -> bool {
+    let mut item = (a, b);
+    if !graph.is_directed() {
+        sorted(&mut item);
+    }
+    matrix.get(&item).cloned().unwrap_or(0) >= val
```
Comment (mtreinish) [inline src/isomorphism/vf2.rs:118]: Do we need to actually clone here? Can't we just match on the get and use 0 if None, something like:
```suggestion
    match matrix.get(&item) {
        Some(count) => count >= val,
        None => 0 >= val, 
    } 
```

**Review by mtreinish — COMMENTED** [review]
Overall LGTM, nice catch and fix. A couple inline comments. Also maybe we should add another fix note about the decrease in memory usage for #367?

**Comment by mtreinish** [comment]
Also when this is ready I think between this and #423 that's probably big enough to start to prepare a 0.10.2 release. I'll create a stable branch and start staging that after this merges.

File: src/isomorphism/vf2.rs (hunk 3 above)
Comment (georgios-ts) [reply src/isomorphism/vf2.rs:79]: Hmm, yeah, it might over allocate but probably by not that much. It's quite difficult to obtain a more tight bound in the number of non-parallel edges. Are you suggesting to not pre-allocate at all?

File: src/isomorphism/vf2.rs (hunk 4 above)
Comment (mtreinish) [reply src/isomorphism/vf2.rs]: True, the overhead should be small, it just stood out as unnecessary. Thanks for updating it.

File: src/isomorphism/vf2.rs (hunk 3 above)
Comment (mtreinish) [reply src/isomorphism/vf2.rs:79]: Yeah, that's what I was getting at. But, thinking about it some more I agree it's probably not a bid deal we basically overallocate 3 usizes for each parallel edge in the graph which will probably hardly be noticeable. Especially compared to the extra allocation overhead for not pre-allocating.

File: src/isomorphism/vf2.rs [hunk 5]
```diff
@@ -41,6 +38,86 @@ use crate::iterators::NodeMap;
...
+    matrix: &HashMap<(NodeIndex, NodeIndex), usize>,
+    a: NodeIndex,
+    b: NodeIndex,
+    val: usize,
+) -> bool {
+    let mut item = (a, b);
+    if !graph.is_directed() {
+        sorted(&mut item);
+    }
+    *matrix.get(&item).unwrap_or(&0) >= val
```
Comment (IvanIsCoding) [inline src/isomorphism/vf2.rs:118]:
```suggestion
    edge_multiplicity(&graph, &matrix, a, b) >= val
```

I think the shorter way makes it more obvious

**Review by mtreinish — APPROVED** [review]
LGTM, thanks for fixing this.
